### ISSUE TITLE
NullPointerException in DailyDoseRepository

### ISSUE THREAD

**Issue by limburgie** [limburgie/inr-diary#39]
```
java.lang.NullPointerException
	at be.webfactor.inrdiary.database.DailyDoseRepository.dao(DailyDoseRepository.java:135)
	at be.webfactor.inrdiary.database.DailyDoseRepository.getDoseByDate(DailyDoseRepository.java:128)
	at be.webfactor.inrdiary.database.DailyDoseRepository.getTodaysDose(DailyDoseRepository.java:67)
	at be.webfactor.inrdiary.database.DailyDoseRepository.toggleTodaysDoseConfirmation(DailyDoseRepository.java:82)
	at be.webfactor.inrdiary.activity.MainActivity$1.onClick(MainActivity.java:68)
	at android.view.View.performClick(View.java:4457)
	at android.view.View$PerformClick.run(View.java:18491)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5336)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by limburgie** [comment]
Cannot be reproduced.
